### ISSUE TITLE
^U delete the entire line and not just the input

### ISSUE THREAD

**Issue by riblanc** [riblanc/kfs#27]
When enabling ECHOCTL, the ^U isn't escaped:
![Screencast from 27-01-2024 03 46 21](https://github.com/riblanc/kfs/assets/59930230/bcfa66ec-8a2d-46e7-90cc-baada46434c0)

**Comment by jgiron42** [comment]
yes this is expected (like in a normal terminal (try with dash)),
what is unexpected on the other hand, is the deletion of the prompt with a ^U

**Comment by riblanc** [comment]
Ok, I hadn't noticed, thanks!
But in that case, how can the shell handle it?? :thinking:

**Comment by jgiron42** [comment]
the problem is in tty, not the shell, I'm currently working on it
