### ISSUE TITLE
Implements ft.mem.alignForwards

### ISSUE THREAD

**Issue by riblanc** [riblanc/kfs#54]
Implements alignForwards on ft.mem.

It's needed for [multiboot.zig:196](https://github.com/riblanc/kfs/blob/99a5ceff1a546c3c04ce5aa066bd8b62851f26d2/src/multiboot.zig#L196) and [multiboot.zig:197](https://github.com/riblanc/kfs/blob/99a5ceff1a546c3c04ce5aa066bd8b62851f26d2/src/multiboot.zig#L208)

**Comment by jgiron42** [comment]
forgot to update functions using std.mem....
